### PR TITLE
Bind specific invoice when paid via Banklink / EveryPay

### LINKED ISSUE #1500: Banklink payments fail
at the very end of banklink payment process after clicking back to merchant user is returned to registrar portal and met there by message "something went wrong". Money is removed form the account, transferred to EIS account, so transaction is successful, but invoice is not marked as paid and the credit is not loaded to registrars prepayment account.

image

there are no errors to be found in the logs. Log excerpt in chat

### PR DESCRIPTION
**Pull request by karlerikounapuu**
Closes #1500 

Creates new BankTransaction in case previous one is already binded with account activity. When attempting to complete transaction, it attempts to bind specific invoice directly (bind_invoice) instead of autobinding (autobind_invoices).

### CODE REVIEW

File: app/models/payment_orders/bank_link.rb [hunk 1]
```diff
@@ -57,6 +57,18 @@ def complete_transaction
         iban: invoice.seller_iban
       )
 
+      # Transaction already autobinded (possibly) invalid invoice
+      if transaction.binded?
```
Comment (yulgolem) [inline app/models/payment_orders/bank_link.rb]: Looks similar to [this method](https://github.com/internetee/registry/pull/1503/files#diff-e501c6a999b2d55ca6d179a0d68bbadfR40) . Maybe we may move it to, say, concern and use the same method of bank transaction creation in both cases?
