### PR TITLE
Admin: fix CSV data output

### LINKED ISSUE #2303: Admin: CSV files should include at least the same set of data available in admin UI
Related to https://github.com/internetee/registry/issues/2275

concerns csv download options in
/admin/domains
/admin/contacts
/admin/invoices
/admin/accounts

CSV download just puts the content of respective main db table into the file so for domains csv its the content of domains table. Problems

* the table used often does not include all the data expected ie domains table includes the object id  of registrant and registrar but not their names and contact data
* the table includes db internal ids that are useless outside of the database 

expected result:
* csv should include all the same data that is returned to the users in admin ui
* additional data can be added in csv, but after the main data and it should not include any data table specific data like row id's

### PR DESCRIPTION
**Pull request by thiagoyoussef**
close #2303

### CODE REVIEW

**Comment by thiagoyoussef** [comment]
Tests are failing because I haven't finished the implementation

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -9,30 +9,6 @@ def env_style
     "background-image: url(#{image_path("#{unstable_env}.png")});"
   end
 
-  def ident_for(contact)
```
Comment (thiagoyoussef) [inline app/helpers/application_helper.rb:12]: I moved this method to `app/models/contact.rb` and changed the name to `ident_human_description`

**Review by OlegPhenomenon — APPROVED** [review]

File: app/models/invoice.rb [hunk 2]
```diff
@@ -128,6 +145,16 @@ def self.create_from_transaction!(transaction)
 
   private
 
+  def receipt_date_status
```
Comment (thiagoyoussef) [inline app/models/invoice.rb:148]: Is the method name clear?

File: app/models/account.rb [hunk 3]
```diff
@@ -12,4 +12,12 @@ class Account < ApplicationRecord
   def activities
     account_activities
   end
+
+  def as_csv_row
+    [id, balance, currency, registrar]
+  end
+
+  def self.csv_header
+    ['Id', 'Balance', 'Currency', 'Registrar'].freeze
```
Comment (OlegPhenomenon) [inline app/models/account.rb:21]: If you decide to freeze this value and use it as global constant, then you should to move it into the top of file and assigned it like constant `CSV_HEADER = ['Id', 'Balance', 'Currency', 'Registrar'].freeze`, otherwise freeze method not make sense to add. So there are two option: first - move to top and make this value as constant, second - remove freeze method

File: app/models/contact.rb [hunk 4]
```diff
@@ -569,4 +569,27 @@ def registrant?
...
+      email,
+      created_at.to_formatted_s(:db),
+      registrar,
+      phone,
+    ]
+  end
+
+  def self.csv_header
+    ['Name', 'ID', 'Ident', 'E-mail', 'Created at', 'Registrar', 'Phone'].freeze
+  end
```
Comment (OlegPhenomenon) [inline app/models/contact.rb:594]: Here is the same, you has identical principles in as_csv_row method and in csv_header, but csv_header looks like you tried to put there constant value. Why?

File: app/models/domain.rb [hunk 5]
```diff
@@ -753,6 +753,35 @@ def contact_emails_verification_failed
...
+
+    contact = ObjectVersionsParser.new(ver).parse if contact.nil? && ver
+
+    contact.try(:name) || 'Deleted'
+  end
+
+  def self.csv_header
+    ['Domain', 'Registrant', 'Valid to', 'Registrar', 'Created at', 'Statuses', 'Contacts code', 'Force delete date', 'Force delete data'].freeze
+  end
+
```
Comment (OlegPhenomenon) [inline app/models/domain.rb:784]: The same

File: app/models/invoice.rb [hunk 6]
```diff
@@ -117,6 +117,23 @@ def e_invoice_sent?
...
+      total,
+      currency,
+      seller_name
+    ]
+  end
+
+  def self.csv_header
+    ['Number', 'Buyer', 'Due Date', 'Receipt Date', 'Issue Date', 'Total', 'Currency', 'Seller Name'].freeze
+  end
+
```
Comment (OlegPhenomenon) [inline app/models/invoice.rb:136]: The same

File: app/models/version/contact_version.rb [hunk 7]
```diff
@@ -4,4 +4,21 @@ class Version::ContactVersion < PaperTrail::Version
...
+      contact.ident_human_description,
+      contact.registrar,
+      event,
+      created_at.to_formatted_s(:db)
+    ]
+  end
+
+  def self.csv_header
+    ['Name', 'ID', 'Ident', 'Registrar', 'Action', 'Created at'].freeze
+  end
```
Comment (OlegPhenomenon) [inline app/models/version/contact_version.rb:23]: again, lol :D

File: app/models/version/domain_version.rb [hunk 8]
```diff
@@ -43,4 +55,8 @@ def self.contact_unlinked_more_than?(contact_id:, period:)
 
     count_by_sql(sql).nonzero?
   end
+
+  def self.csv_header
+    ['Name', 'Registrant', 'Registrar', 'Action', 'Created at'].freeze
+  end
```
Comment (OlegPhenomenon) [inline app/models/version/domain_version.rb:61]: or noooo, not again :D

**Review by OlegPhenomenon — CHANGES_REQUESTED** [review]

File: app/models/account.rb (hunk 3 above)
Comment (thiagoyoussef) [reply app/models/account.rb:21]: That's true! I will remove the freeze method ;)
