### PR TITLE
Disputes: fix for registration of disputed domains

### LINKED ISSUE #2169: Disputes: registration of disputed domain fails with correct password
Regsitration of disputed domain requires correct reservation password. The process has been broken at some point as registering a domain in disputes list with correct password results in credit removed, disputed domain removed from disputed list but the registration request failing with 

```
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lib/schemas/epp-ee-1.0.xsd">
  <response>
    <result code="2202">
      <msg lang="en">Invalid authorization information; invalid reserved&gt;pw value</msg>
    </result>
    <trID>
      <clTRID>Märi Änn PR-1632502822</clTRID>
      <svTRID>ccReg-6355587861</svTRID>
    </trID>
  </response>
</epp>
```

sample request:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="https://epp.tld.ee/schema/epp-ee-1.0.xsd">
  <command>
    <create>
      <domain:create xmlns:domain="https://epp.tld.ee/schema/domain-ee-1.1.xsd">
        <domain:name>dispute.ee</domain:name>
        <domain:period unit="y">1</domain:period>
        <domain:registrant>BEST:C29B28C0</domain:registrant>
        <domain:contact type="admin">BEST:219D698B</domain:contact>
      </domain:create>
    </create>
    <extension>
      <eis:extdata xmlns:eis="https://epp.tld.ee/schema/eis-1.0.xsd">
        <eis:reserved>
          <eis:pw>test</eis:pw>
        </eis:reserved>
      </eis:extdata>
    </extension>
    <clTRID>Märi Änn PR-1632502822</clTRID>
  </command>
</epp>
```

### PR DESCRIPTION
**Pull request by DinSmol**
close #2169

### CODE REVIEW

File: app/interactions/whois/update.rb [hunk 1]
```diff
@@ -33,7 +33,11 @@ def determine_class
     end
 
     def find_record(klass, name)
-      klass == DNS::Zone ? klass.find_by(origin: name) : klass.find_by(name: name)
+      if klass == Dispute.active
```
Comment (yulgolem) [inline app/interactions/whois/update.rb:36]: Since that's not a class anymore, but more of some scoped collection, I suppose we should rename this arg to something like `scoped_collection` just to not have a semantic confusion.
Same with `determine_class` function

**Review by yulgolem — APPROVED** [review]

**Review by yulgolem — APPROVED** [review]
