### PR TITLE
Fix for contact birth date validation

### LINKED ISSUE #1796: Registrar: Validation birthday field in Contact - Allow a non-existent date of birth
Steps:
1. Go to contacts and create a contact
2. Choose any country instead of Estonia
3. In the type field select the date of birth
4. Type tomorrow or any future day in the birthday field

The form creates a contact with a date of birth that will happen in the future

UPDATE:
Also the form skips non-existent dates, for example 0000-34-35

### PR DESCRIPTION
**Pull request by DinSmol**
close #1796

### CODE REVIEW

File: app/models/epp/contact.rb [hunk 1]
```diff
@@ -16,6 +16,26 @@ def manage_permissions
...
+    return unless Depp::Contact::SELECTION_TYPES[2].include?(ident_type)
+
+    if (Date.parse(ident) rescue ArgumentError) == ArgumentError
+      add_epp_error('2308', nil, nil, I18n.t('epp.contacts.errors.valid_ident_date_format'))
+      @error = true
+      return
+    end
+
+    contact_ident_date = Date.parse(ident)
+    valid_time_range = (Date.today - 125.years)...(Date.tomorrow - 18.years)
```
Comment (yulgolem) [inline app/models/epp/contact.rb:31]: Let's save it in some constant or Value Object.
And why 18 years ago? Do we have any legal regulations on that?

**Review by yulgolem — CHANGES_REQUESTED** [review]

File: app/models/epp/contact.rb (hunk 1 above)
Comment (DinSmol) [reply app/models/epp/contact.rb:31]: I am not aware of any legal regulations regarding this. This is just my guess. I'll ask Timo about it.

**Review by yulgolem — APPROVED** [review]
